title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://danlu1.github.io/test_just_to_docs


aux_links:
  Template Repository: https://github.com/danlu1/test_just_to_docs
